categories_to_be_scanned = [5, 4]
number_of_days_for_backtest = 101
number_of_days_prev_data_required = 365
# number_of_days_prev_data_required = 365 * 1
scan_stocks_category_array = [5, 4, 3, 2]
scan_stocks_array = [['BAJFINANCE', '81153']]
max_percentage_change_per_day = 1
avg_volume_multiplier = 1.5
number_of_jobs_in_one_lot = 1
